### PR TITLE
Support Cypress 10

### PR DESCRIPTION
**Pull request by simonsmith**
* Update `peerDependency` version in `package.json`
* Update some packages to later versions
* Update the `examples` directory to work with Cypress >10

If you're open to it I was also thinking about rewriting it with TS so we no longer need the `@types/cypress-image-snapshot` package. That can be a separate pull request though

### CODE REVIEW

**Comment by vitkarpov** [comment]
Upvote! That'd be awesome to get 🚀

**Review by iMayuuR — APPROVED** [review]

**Comment by CoreyGahafer** [comment]
@simonsmith I'm coming across one issue with this and maybe you can help me with it. Prior to Cypress 10, we were using a custom `integrationFolder` path and with Cypress 10, this is no longer an option. With that being the case, is there a way to set a similar base path like was previously being leveraged with the `integrationFolder`?

**Comment by sosog** [comment]
Hi, you have a similar PR without activity https://github.com/jaredpalmer/cypress-image-snapshot/pull/267

**Comment by simonsmith** [comment]
Removed my fork and recreated as standalone - https://github.com/simonsmith/cypress-image-snapshot

**Pull request closed without merging**
